# https://stackoverflow.com/q/77826751
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  configPath: /etc/config/prometheus.yml
  defaultFlagsOverride:
  - --enable-feature=agent
  - --config.file=/etc/config/prometheus.yml
  extraFlags:
  - web.enable-lifecycle
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s
  persistentVolume:
    enabled: false
  remoteWrite:
  - basic_auth:
      password: promuser
      username: prom
    url: https://prometheus.pridesys.duckdns.org//api/v1/write
serverFiles:
  prometheus.yml:
    rule_files: []

# helm upgrade --install prometheus prometheus-community/prometheus -f values.agent.yml -n monitoring --create-namespac