# https://github.com/prometheus-community/helm-charts/issues/1519
# https://promlabs.com/blog/2022/12/15/understanding-duplicate-samples-and-out-of-order-timestamp-errors-in-prometheus/
server:
  enabled: true
  defaultFlagsOverride:
    - --config.file=/etc/config/prometheus.yml
  extraFlags:
    - web.enable-lifecycle
    - storage.tsdb.wal-compression
  configPath: /etc/config/prometheus.yml
  persistentVolume:
    enabled: true
    size: 1Gi 
  remoteWrite:
    - url: "https://prometheus.pridesys.duckdns.org/api/v1/write"
      basic_auth:
        username: "promuser"
        password: "prom"
      write_relabel_configs:
        - action: replace
          source_labels: []
          target_label: source
          replacement: "agent"

serverFiles:
  prometheus.yml:
    rule_files: []

prometheus-pushgateway:
  enabled: false

alertmanager:
  enabled: false