prometheus:
 # agentMode: true
  logLevel: debug
  prometheusSpec:
    remoteWrite:
      - url: https://prometheus.pridesys.duckdns.org/api/v1/write
        basicAuth:
          username:
            name: prometheus-extra-secret
            key: username
          password:
            name: prometheus-extra-secret
            key: password
        messageVersion: V2.0
        writeRelabelConfigs:
          - action: replace
            sourceLabels: []
            targetLabel: source
            replacement: "kube-agent"

  extraSecret:
    name: prometheus-extra-secret
    data:
      username: promuser
      password: prom

alertmanager:
  enabled: false

grafana:
  enabled: true

# defaultRules: 
#   create: false
