version: '3.8'
services:
  prometheus-central:
    image: prom/prometheus:latest
    container_name: prometheus-central
    volumes:
      - ./prom-central.yml:/etc/prometheus/prometheus.yml
      - ./basic-auth:/etc/prometheus/auth
      - ./web-config.yml:/etc/prometheus/web-config.yml
      - prometheus-central-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web-config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver" # enable remote write
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana native port (optional)
    volumes:
      - grafana_data:/var/lib/grafana # Persist Grafana data
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default admin password
    restart: unless-stopped

  prometheus-agent-1:
    image: prom/prometheus:latest
    container_name: prometheus-agent-1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=agent'
    volumes:
      - ./prom-agent-1.yml:/etc/prometheus/prometheus.yml
      - prometheus-agent-1-data:/prometheus
    ports:
      - "9091:9090" # Optional, for local debugging
    restart: unless-stopped

volumes:
  grafana_data:
  prometheus-central-data:
  prometheus-agent-1-data:
